Version: 1.1.0
thephpleague/flysystem pull request #1183
Opened 2020-08-08 21:56 UTC by frankdejonge

2020-08-08 22:36 UTC, GrahamCampbell requested changes
Left some minor comments. :)

2020-08-08 22:36 UTC, GrahamCampbell commented on composer.json
> +        "php": ">=7.2.5",
Maybe go with `^7.2.5 || ^8.0`?

2020-08-08 22:36 UTC, GrahamCampbell commented on tests/ForcedCopyPluginTests.php
> +    // use \PHPUnitHacks;
These should probably be deleted from the code. They remain in the git history, if we wanna get them back? ;)

2020-08-08 22:36 UTC, GrahamCampbell commented on tests/FtpTests.php
> +        if (substr(PHP_VERSION, 0, 2) === '8.') {
`PHP_MAJOR_VERSION > 7`?

2020-08-08 22:36 UTC, GrahamCampbell commented on tests/FtpTests.php
> +        if (substr(PHP_VERSION, 0, 2) === '8.') {
Can also be implemented with a `@requires PHP < 8` annotation.

2020-08-08 22:36 UTC, GrahamCampbell commented on tests/FtpTests.php
> +        $this->expectException(RuntimeException::class);
Why is there an assert equals on the last line. Is that not reachable?

2020-08-08 22:36 UTC, GrahamCampbell commented on tests/FtpTests.php
> +        $this->expectException(RuntimeException::class);
Also, the reason PHPUnit introduced expectException and ditched the annotation was so that people could put this just above the line of code they expected to crash, rather than at the start of the whole test method. The idea being then that the code cannot crash earlier than expected, and also unreachable code is meant to be less likely to be written in error. ;)

2020-08-09 06:57 UTC, frankdejonge commented on tests/FtpTests.php
> +        $this->expectException(RuntimeException::class);
This was just a super old "copy-paste-adjust" from a PR, about 4 years ago.

2020-08-09 06:58 UTC, frankdejonge commented on tests/FtpTests.php
> +        if (substr(PHP_VERSION, 0, 2) === '8.') {
Adjusted 👍

2020-08-09 07:00 UTC, frankdejonge commented
@GrahamCampbell thanks for the review 👍 much appreciated. I've pushed changed to handle them.

2020-08-09 10:02 UTC, GrahamCampbell requested changes

2020-08-09 10:02 UTC, GrahamCampbell commented on composer.json
> +        "league/mime-type-detection": "^1.3"
https://github.com/thephpleague/mime-type-detection/pull/1 will be needed so that `league/mime-type-detection` doesn't block installation on PHP 8. :)

2020-08-09 11:13 UTC, frankdejonge commented on composer.json
> +        "league/mime-type-detection": "^1.3"
I've merged your PR and tagged 1.4.0, so we're good 👍

2020-08-09 11:36 UTC, GrahamCampbell commented on src/Util/MimeType.php
>   * @internal
This class is internal, so nobody can call the useDetector stuff?

2020-08-09 11:37 UTC, frankdejonge commented on src/Util/MimeType.php
>   * @internal
People can use it if they need to, however, it falls outside of the BC promise, so it's at their own risk.

2020-08-09 11:38 UTC, frankdejonge commented on src/Util/MimeType.php
>   * @internal
It's all going to be different in V2 anyway, where this is just a normal injected dependency, not this global scope iffiness.

2020-08-09 11:43 UTC, GrahamCampbell commented on src/Util/MimeType.php
>   * @internal
Fair enough. :)

2020-08-09 11:43 UTC, GrahamCampbell approved these changes
🚢

2020-08-09 15:57 UTC, merged