Use $config parameter in copy operation
thephpleague/flysystem pull request #1262
Opened 2021-01-26 08:23 UTC by lboynton

I noticed that when copying a file, the `$config` param is not used. This is a problem if you require the object to be encrypted, for example. This fixes the problem by merging the config with the config that the class is instantiated with.

2021-02-01 21:55 UTC, Nyholm requested changes
Thank you for this PR. 

Could you add a test too please?

2021-02-01 22:23 UTC, lboynton commented
> Thank you for this PR.
> 
> Could you add a test too please?

I have added a test, how do I run AWS tests? It doesn't look like Github actions runs any.

2021-02-01 22:28 UTC, Nyholm commented
The tests are running. See https://github.com/thephpleague/flysystem/pull/1262/checks?check_run_id=1810393450#step:13:1

To run the Aws tests locally you need to define some environment variables: https://github.com/thephpleague/flysystem/blob/317a3951ffca189da1c9774c32567d1973619fef/src/AwsS3V3/AwsS3V3AdapterTest.php#L80-L83

2021-02-01 22:31 UTC, Nyholm commented
> This is a problem if you require the object to be encrypted, for example.

I read form the tests, that you want to copy a file and add encryption at the same time? Is that really correct? The end result of `copy()` will not be a copy of the original file.

2021-02-01 23:15 UTC, lboynton commented
Originally yes, because I want to use a bucket policy that enforces encryption. However in the test I have used an example of modifying the content type of a file through a move operation, as this is easier to make assertions on in the test code.

2021-02-01 23:39 UTC, Nyholm commented
What I'm wondering is, could you download the file from s3 with no encryption, get the stream a d then with a new Filesystem object (with encryption) upload the stream. 

The copy function is for cloning a file. If you modify the properties (or content in the case of encryption) it is not a clone anymore.

2021-02-07 15:51 UTC, lboynton commented
Yes I could. But this change just exposes functionality that the AWS S3 CLI provides itself: https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

Happy to close this as a "won't fix" if this is not desired, but it seems logical to me to provide the same functionality.

2021-02-09 21:05 UTC, frankdejonge commented
@lboynton Hi,

I'm open to this PR but I would like to make one change, the explicit `if` statement + option setting is not needed as there is already a mechanism to include items from the config. Instead, please add `'MetadataDirective'` to the AVAILABLE_OPTIONS constant, this will make sure the option is copied over from the config object to the options array.

2021-02-09 21:09 UTC, frankdejonge commented
I'll amend the changes myself, about to tag a new release so this can be shipped as well then.

2021-02-09 21:10 UTC, merged

2021-02-09 21:12 UTC, lboynton commented
Thanks @frankdejonge 

Just to explain my reasoning for doing it that way - I believe `MetadataDirective` is only valid when doing certain actions like copy? So may not be valid for all S3 API operations. But I only looked at it briefly, so could be wrong.