[feature]: optimize MountManager to make it extendable
thephpleague/flysystem pull request #1263
Opened 2021-01-26 11:57 UTC by EvgenyBarinov

This modification can help to reuse MountManager or use it in more flexible way.
Using separator in const can be used to provide another pattern for filepath storages

2021-02-01 21:59 UTC, Nyholm requested changes
Thank you for this PR. 

Can you explain **why** these modifications are needed? Why do you need to extend MountManager? 

This PR is also missing tests.

2021-02-01 21:59 UTC, Nyholm commented on src/MountManager.php
> +    protected const FILESYSTEM_PATH_SEPARATOR = '://';
Could you help me understand in what scenario this needs to be changed?

2021-02-01 22:03 UTC, Nyholm commented
I have read #1250 and Im not sure I understand the scenario. 

In general, one should always keep things private. One should use composition over inheritance. I also prefer `final`.

2021-02-02 06:51 UTC, Eugentis commented on src/MountManager.php
> +    protected const FILESYSTEM_PATH_SEPARATOR = '://';
Current implementation is very strict about uri format but in some system you can use some other separator for server and filepath. It depends on project.

As I can see the most flexible way can be some regex patter to store some specific pattern with required parts.
For example current pattern can be described in pattern like [this](https://regex101.com/r/2sPIri/1) but in some projects you need to keep more information in uri - project name for example or smth like this

I understand this pattern is not ideal now and can be modified but it is more flexible as I can see and can be used in your method `\League\Flysystem\MountManager::determineFilesystemAndPath` for example

2021-02-02 07:02 UTC, Eugentis commented
> I have read #1250 and Im not sure I understand the scenario.
> 
> In general, one should always keep things private. One should use composition over inheritance. I also prefer `final`.

If we are talking about some project it is suitable but if you would like to provide reusable components you should provide more flexible components.

Current implementation of MountManager is not reusable by next reasons:
1. Private doesn't allow to extend it
2. Current implementation can't provide dynamic mounting new filesystems - it is restrict mounting management after MountManager creation. By this reason MountManager is not suitable for some dynamic mounting.
* it can be a problem in frameworks with DI - you need to prepare some initialization methods instead of mapping by some interfaces

Now I am working on component for providing work with multiple system depends on provided configuration and your current implementation suitable for me only by 70-80% but I need to use some modifications provided by different business logic requirements. I would like to use some specific component based on MountManager but it was restricted by private.
From my point of view it is bad practice if I will have class similar to MountManager in most of codebase...

2021-02-02 07:32 UTC, Nyholm commented
> If we are talking about some project it is suitable but if you would like to provide reusable components you should provide more flexible components.

A component can be flexible without inheritance. 

> Private doesn't allow to extend it

I see that as a good thing. 

> Current implementation can't provide dynamic mounting new filesystems

That is also a good thing. Services should be immutable. 

> it can be a problem in frameworks with DI - you need to prepare some initialization methods instead of mapping by some interfaces

A good DI will prefer initialization methods. And you do have the `FilesystemOperator` interface...

------------

It sounds like you want to wedge in some use of the MountManager in a way it is not intended to. This makes your code feel bad and instead of fixing your architecture, you want to make the MountManager worse by calling in "more flexible". 

I understand your frustration, I also don't think you will see my point of view. I recommend you to copy the `MountManager` and modify it so it fits your specific needs. 

I vote for closing this PR.

2021-02-02 07:35 UTC, Eugentis commented
> Thank you for this PR.
> 
> Can you explain **why** these modifications are needed? Why do you need to extend MountManager?
> 
> This PR is also missing tests.

Tests were added. Mount Manager coverage 100%

2021-02-02 07:35 UTC, Eugentis commented
New functionality added for https://github.com/thephpleague/flysystem/issues/1266

2021-02-02 07:48 UTC, Eugentis commented
I suppose in nearest future you will add similar functionality in MountManager. In v1 this class was more friendly and your users will request to make it more flexible to use at least.
Take a look at 1266 for example

2021-02-02 09:59 UTC, Nyholm commented
> New functionality added for #1266 for v2

Adding more features in this PR will not make it easer to merge. A general rule is "One feature => One PR".

2021-02-02 18:36 UTC, frankdejonge commented
I'm not in favour of adding this functionality in the library. If you need a mount manager which has these capabilities I would advice to implement it yourself. The mount manager used to have these capabilities and I have negative experiences with that setup. For 2.0 there was a request for the mount manager. If you need a mount manager with dynamic filesystems I suggest to create a factory where you can resolve a mount manager with the needed filesystem instead.

2021-02-06 12:49 UTC, Eugentis commented
vf

2021-02-06 12:49 UTC, Eugentis commented
Ok
Please close this PR

2021-02-06 13:50 UTC, closed without merging