Removed generic exception from phpdoc
thephpleague/flysystem pull request #1306
Opened 2021-05-04 12:20 UTC by dakur

Closes #1304

2021-05-13 06:09 UTC, Nyholm requested changes
I dont think it is a good idea to remove `FilesystemException` from everywhere. The exception can be thrown as stated in https://github.com/thephpleague/flysystem/issues/1304#issuecomment-831944486. 

Also, this brings no clear advantage. 

Im happy with a PR that just adds `UnableToCheckFileExistence` on `fileExists()`

2021-05-13 06:09 UTC, Nyholm commented on src/FilesystemAdapter.php
> +     * @throws UnableToCheckFileExistence
I like that you added this line, but dont remove the `FilesystemException`.

2021-07-13 05:03 UTC, dakur commented
> 
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

I plan to reply

2021-09-22 06:25 UTC, dakur commented
Sorry, I can't return to this anymore. But the idea was sketched in #1304 and https://github.com/thephpleague/flysystem/issues/1304#issuecomment-832474936

2021-11-20 10:24 UTC, closed without merging